version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: myprodpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: strapi
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
